cryptotracker_app/cryptocurrencies/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('cryptocurrencies/<str:pk>/', views.CryptocurrencyDetailView.as_view(), name='crypto_detail'),
    path('alerts/<uuid:pk>/update/', views.CryptocurrencyAlertUpdateView.as_view(), name='crypto_alert_update'),
    path('alerts/<uuid:pk>/delete/', views.CryptocurrencyAlertDeleteView.as_view(), name='crypto_alert_delete'),
]

cryptotracker_app/cryptocurrencies/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


class Cryptocurrency(models.Model):
    id = models.CharField(max_length=300, primary_key=True)
    name = models.CharField(max_length=500)
    symbol = models.CharField(max_length=50)
    image = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} ({self.symbol.upper()})'


class CryptocurrencyAlert(models.Model):
    ALERT_TYPES = (
        ('price_above', 'Preço acima de'),
        ('price_below', 'Preço abaixo de'),
    )

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    cryptocurrency = models.ForeignKey(Cryptocurrency, on_delete=models.CASCADE, related_name='alerts')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='alerts')
    alert_type = models.CharField(max_length=30, choices=ALERT_TYPES)
    value = models.DecimalField(max_digits=20, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Alerta de '{self.user.username}' para '{self.cryptocurrency.name}'"


class CryptocurrencyPrice(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    cryptocurrency = models.ForeignKey(Cryptocurrency, on_delete=models.CASCADE, related_name='prices')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    price_change_percentage_24h = models.DecimalField(max_digits=20, decimal_places=2)
    market_rank = models.IntegerField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.cryptocurrency.symbol}: ${self.price}"

cryptotracker_app/cryptocurrencies/forms.py
from django import forms
from .models import CryptocurrencyAlert


class CryptocurrencyAlertForm(forms.ModelForm):
    class Meta:
        model = CryptocurrencyAlert
        fields = '__all__'
        widgets = {
            'alert_type': forms.Select(attrs={'class': 'form-control'}),
            'value': forms.NumberInput(attrs={'class': 'form-control'}),
            'cryptocurrency': forms.HiddenInput(),
            'user': forms.HiddenInput()
        }
        labels = {
            'alert_type': 'Tipo de Alerta',
            'value': 'Valor'
        }

cryptotracker_app/cryptocurrencies/views.py
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.core.paginator import Paginator
from django.db.models import OuterRef, Subquery
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import ModelFormMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import CryptocurrencyPrice, Cryptocurrency, CryptocurrencyAlert
from .forms import CryptocurrencyAlertForm


class HomeView(LoginRequiredMixin, ListView):
    template_name = 'home.html'
    context_object_name = 'cryptos_price'

    def get_queryset(self):
        latest_price_subquery = CryptocurrencyPrice.objects.filter(
            cryptocurrency=OuterRef('cryptocurrency')
        ).values('id')[:1]

        latest_prices = CryptocurrencyPrice.objects.filter(
            id__in=Subquery(latest_price_subquery)
        )
        return latest_prices

    def __get_queryset_by_search_method(self, queryset):
        crypto_name = self.request.GET.get('cryptocurrency')
        if crypto_name:
            return queryset.filter(cryptocurrency__name__icontains=crypto_name)
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()

        context['search_queryset'] = self.__get_queryset_by_search_method(queryset)
        if context['search_queryset']:
            search_paginator = Paginator(context['search_queryset'], 5)
            search_page = search_paginator.get_page(self.request.GET.get('search_page'))
            context['search_page'] = search_page

        context['trending_cryptos'] = queryset.order_by('market_rank')[:5]
        context['most_expensive_cryptos'] = queryset.order_by('-price')[:5]
        context['most_devalued_cryptos'] = queryset.order_by('price_change_percentage_24h')[:5]
        context['most_valued_cryptos'] = queryset.order_by('-price_change_percentage_24h')[:5]
        return context


class CryptocurrencyDetailView(LoginRequiredMixin, ModelFormMixin, DetailView):
    model = Cryptocurrency
    template_name = "cryptocurrency_detail.html"
    form_class = CryptocurrencyAlertForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context['current_price'] = obj.prices.first()
        context['user_crypto_alerts'] = CryptocurrencyAlert.objects.filter(
            cryptocurrency=obj,
            user=self.request.user
        )
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial'] = {
            'cryptocurrency': self.kwargs.get('pk'),
            'user': self.request.user
        }
        return kwargs

    def post(self, request, *args, **kwargs):
        cryptocurrency_id = request.POST.get('cryptocurrency')
        user_id = request.POST.get('user')
        alert_type = request.POST.get('alert_type')
        value = request.POST.get('value')

        CryptocurrencyAlert.objects.create(
            cryptocurrency=get_object_or_404(Cryptocurrency, pk=cryptocurrency_id),
            user=get_object_or_404(User, pk=user_id),
            alert_type=alert_type,
            value=value
        )
        return redirect(request.path)


class CryptocurrencyAlertUpdateView(LoginRequiredMixin, UpdateView):
    model = CryptocurrencyAlert
    template_name = "cryptocurrency_alert_update.html"
    form_class = CryptocurrencyAlertForm

    def get_success_url(self):
        return reverse_lazy('crypto_detail', kwargs={'pk': self.get_object().cryptocurrency.id})


class CryptocurrencyAlertDeleteView(LoginRequiredMixin, DeleteView):
    model = CryptocurrencyAlert
    template_name = "cryptocurrency_alert_delete.html"

    def get_success_url(self):
        return reverse_lazy('crypto_detail', kwargs={'pk': self.get_object().cryptocurrency.id})

cryptotracker_app/cryptocurrencies/templates/cryptocurrency_alert_delete.html
{% extends 'base.html' %}
{% block title %}Editar alerta{% endblock title %}

{% block content %}
<div class="d-flex align-items-center justify-content-start gap-3">
    <h2>Tem certeza que deseja deletar o seguinte alerta:
    <div class="text-decoration-none btn btn-primary">
        <div class="justify-content-center align-items-center d-flex" style="max-width: 300px">
            <p class="m-0"><span class="fw-bold">{{ object.get_alert_type_display|safe }}</span> ${{ object.value }}</p>
        </div>
    </div>
    ?</h2>
</div>
<h6 class="text-secondary"><span class="fw-bold">Criptomoeda: </span>{{ object.cryptocurrency.name }} ({{ object.cryptocurrency.symbol }})</h6>

<div class="mb-5">
    <form action="{% url 'crypto_alert_delete' object.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Sim, excluir alerta</button>
    </form>
</div>

<a href="{% url 'crypto_detail' object.cryptocurrency.id %}" class="btn btn-secondary"> &laquo; Voltar para informações da criptomoeda</a>


{% endblock content %}

cryptotracker_app/cryptocurrencies/templates/cryptocurrency_alert_update.html
{% extends 'base.html' %}
{% block title %}Editar alerta{% endblock title %}

{% block content %}
<div class="d-flex align-items-center justify-content-start gap-3">
    <h2>Atualizando o seguinte alerta: </h2>
    <div class="text-decoration-none btn btn-primary">
        <div class="justify-content-center align-items-center d-flex" style="max-width: 300px">
            <p class="m-0"><span class="fw-bold">{{ object.get_alert_type_display|safe }}</span> ${{ object.value }}</p>
        </div>
    </div>
</div>
<h6 class="text-secondary"><span class="fw-bold">Criptomoeda: </span>{{ object.cryptocurrency.name }} ({{ object.cryptocurrency.symbol }})</h6>

<div class="card mb-5">
    <form action="{% url 'crypto_alert_update' object.id %}" method="post">
        <div class="card-body">
          {% csrf_token %}
          {{ form.as_p }}
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-success me-2">Salvar mudanças</button>
          <a href="{% url 'crypto_alert_delete' object.id %}" class="btn btn-danger">Excluir alerta</a>
        </div>
    </form>
</div>

<p>
    
</p>

<a href="{% url 'crypto_detail' object.cryptocurrency.id %}" class="btn btn-secondary"> &laquo; Voltar para informações da criptomoeda</a>


{% endblock content %}

cryptotracker_app/cryptocurrencies/templates/cryptocurrency_detail.html
{% extends 'base.html' %}
{% block title %}Informações de {{object.name}}{% endblock title %}

{% block content %}
<h1 class="text-success">{{ object.name }} ({{ object.symbol }})</h1>
<hr>
{% if user_crypto_alerts %}
<div class="mb-2">
  <h4 class="mb-0">Você tem o(s) seguinte(s) alerta(s) para esta criptomoeda:</h4>
  <p class="text-secondary">Clique no alerta caso deseje editá-lo ou excluí-lo.</p>
</div>
<div class="mb-5 row">
{% for alert in user_crypto_alerts %}
<div class="col-md-2 col-4">
  <a href="{% url 'crypto_alert_update' alert.id %}" class="text-decoration-none btn btn-primary">
    <div class="justify-content-center align-items-center d-flex">
        <p class="m-0"><span class="fw-bold">{{ alert.get_alert_type_display|safe }}</span> ${{ alert.value }}</p>
    </div>
  </a>
</div>
{% endfor %}
</div>
{% else %}
<p class="text-secondary">Você não tem nenhum alerta para esta criptomoeda.</p>
{% endif %}
<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4 p-3 d-flex align-items-center justify-content-center">
        <img src="{{ object.image }}" class="img-fluid rounded-start" alt="Image of {{ object.name }}">
      </div>
      <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <p class="card-text">
                <ul>
                    <li><span class="fw-bold">Preço atual: </span>${{ current_price.price }}</li>
                    <li>
                        <span class="fw-bold">Variação (últimas 24hrs, em %): </span>
                        <span class="{% if current_price.price_change_percentage_24h < 0%}text-danger{%else%}text-success{%endif%}">{{ current_price.price_change_percentage_24h }}%</span>
                    </li>
                    <li><span class="fw-bold">Ranking atual no mercado: </span>{{ current_price.market_rank }}º</li>
                </ul>
                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modalForm">Ativar alerta</button>
            </p>
          <p class="card-text"><small class="text-body-secondary">Atualizado há {{ current_price.timestamp|timesince }}</small></p>
        </div>
      </div>
    </div>
</div>

<div class="modal fade" id="modalForm" tabindex="-1" aria-labelledby="modalFormLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="modalFormLabel">Criar alerta para {{object.name}}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'crypto_detail' object.id %}" method="post">
        <div class="modal-body">
          {% csrf_token %}
          {{ form.as_p }}
        
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
    </div>
  </div>
</div>

<a href="{% url 'home' %}" class="btn btn-secondary">&laquo; Voltar para a página inicial</a>

{% endblock content %}

{% block scripts %}
<script>
  document.addEventListener('DOMContentLoaded', ()=>{
      if(document.URL.includes('showmodal=true')){
        const modal = new bootstrap.Modal(document.getElementById('modalForm'), {});
        modal.show();
      }
  });
</script>
{% endblock scripts %}

cryptotracker_app/cryptocurrencies/templates/home.html
{% extends 'base.html' %}
{% block title %}Página Inicial{% endblock title %}

{% block content %}
<h1>Criptomoedas</h1>
<div class="my-3">
    <form method="get" action="{% url 'home' %}" class="input-group">
        <input type="search" name="cryptocurrency" id="cryptocurrency" class="form-control" placeholder="Pesquisar criptomoeda" value="{{ request.GET.cryptocurrency }}">
        <button type="submit" class="btn btn-success input-group-text">🔍</button>
    </form>
    {% if search_page %}
    <h5 class="my-2">Resultados encontrados:</h5>
    <div class="card-group mb-5">
        {% for crypto in search_page %}
        <div class="card justify-content-center align-items-center" style="width: 18rem;">
            <img src="{{ crypto.cryptocurrency.image }}" class="card-img-top pt-3" alt="Imagem de {{ crypto.cryptocurrency.name }}" style="max-width: 50px;">
            <div class="card-body">
                <h5 class="card-title">{{ crypto.cryptocurrency.name }} ({{ crypto.cryptocurrency.symbol }})</h5>
                <p class="card-text">
                Preço atual: ${{ crypto.price }}<br>
                Variação (24h): <span class="{% if crypto.price_change_percentage_24h < 0%}text-danger{%else%}text-success{%endif%}">{{ crypto.price_change_percentage_24h }}%</span>
                </p>
                <div>
                    <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}" class="btn btn-primary btn-sm">Ver mais</a>
                    <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}?showmodal=true" class="btn btn-warning btn-sm">Ativar alerta</a>
                </div>
                <small class="text-secondary">Atualizado há {{ crypto.timestamp|timesince }}</small>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if search_page.paginator.num_pages > 1 %}
    {% include 'components/_pagination.html' with page_obj=search_page page_name='search_page' obj_value=request.GET.cryptocurrency search_obj='cryptocurrency'%}
    {% endif %}
    {% endif %}
</div>
<h5>Em alta 🔥</h5>
<hr>
<div class="card-group mb-5">
{% for crypto in trending_cryptos %}
<div class="card justify-content-center align-items-center" style="width: 18rem;">
    <img src="{{ crypto.cryptocurrency.image }}" class="card-img-top pt-3" alt="Imagem de {{ crypto.cryptocurrency.name }}" style="max-width: 50px;">
    <div class="card-body">
        <h5 class="card-title">{{ crypto.cryptocurrency.name }} ({{ crypto.cryptocurrency.symbol }})</h5>
        <p class="card-text">
        Preço atual: ${{ crypto.price }}<br>
        Variação (24h): <span class="{% if crypto.price_change_percentage_24h < 0%}text-danger{%else%}text-success{%endif%}">{{ crypto.price_change_percentage_24h }}%</span>
        </p>
        <div>
            <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}" class="btn btn-primary btn-sm">Ver mais</a>
            <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}?showmodal=true" class="btn btn-warning btn-sm">Ativar alerta</a>
        </div>
        <small class="text-secondary">Atualizado há {{ crypto.timestamp|timesince }}</small>
    </div>
</div>


{% endfor %}
</div>
<h5>Mais caras 💲</h5>
<hr>
<div class="card-group mb-5">
    {% for crypto in most_expensive_cryptos %}
    <div class="card justify-content-center align-items-center" style="width: 18rem;">
        <img src="{{ crypto.cryptocurrency.image }}" class="card-img-top pt-3" alt="Imagem de {{ crypto.cryptocurrency.name }}" style="max-width: 50px;">
        <div class="card-body">
            <h5 class="card-title">{{ crypto.cryptocurrency.name }} ({{ crypto.cryptocurrency.symbol }})</h5>
            <p class="card-text">
            Preço atual: ${{ crypto.price }}<br>
            Variação (24h): <span class="{% if crypto.price_change_percentage_24h < 0%}text-danger{%else%}text-success{%endif%}">{{ crypto.price_change_percentage_24h }}%</span>
            </p>
            <div>
                <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}" class="btn btn-primary btn-sm">Ver mais</a>
                <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}?showmodal=true" class="btn btn-warning btn-sm">Ativar alerta</a>
            </div>
            <small class="text-secondary">Atualizado há {{ crypto.timestamp|timesince }}</small>
        </div>
</div>
{% endfor %}
</div>

<h5>Maiores desvalorizações de preço nas últimas 24h (em %) 📉</h5>
<hr>
<div class="card-group mb-5">
    {% for crypto in most_devalued_cryptos %}
    <div class="card justify-content-center align-items-center" style="width: 18rem;">
        <img src="{{ crypto.cryptocurrency.image }}" class="card-img-top pt-3" alt="Imagem de {{ crypto.cryptocurrency.name }}" style="max-width: 50px;">
        <div class="card-body">
            <h5 class="card-title">{{ crypto.cryptocurrency.name }} ({{ crypto.cryptocurrency.symbol }})</h5>
            <p class="card-text">
            Preço atual: ${{ crypto.price }}<br>
            Variação (24h): <span class="{% if crypto.price_change_percentage_24h < 0%}text-danger{%else%}text-success{%endif%}">{{ crypto.price_change_percentage_24h }}%</span>
            </p>
            <div>
                <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}" class="btn btn-primary btn-sm">Ver mais</a>
                <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}?showmodal=true" class="btn btn-warning btn-sm">Ativar alerta</a>
            </div>
            <small class="text-secondary">Atualizado há {{ crypto.timestamp|timesince }}</small>
        </div>
</div>
{% endfor %}
</div>

<h5>Maiores valorizações de preço nas últimas 24h (em %) 📈</h5>
<hr>
<div class="card-group mb-5">
    {% for crypto in most_valued_cryptos %}
    <div class="card justify-content-center align-items-center" style="width: 18rem;">
        <img src="{{ crypto.cryptocurrency.image }}" class="card-img-top pt-3" alt="Imagem de {{ crypto.cryptocurrency.name }}" style="max-width: 50px;">
        <div class="card-body">
            <h5 class="card-title">{{ crypto.cryptocurrency.name }} ({{ crypto.cryptocurrency.symbol }})</h5>
            <p class="card-text">
            Preço atual: ${{ crypto.price }}<br>
            Variação (24h): <span class="{% if crypto.price_change_percentage_24h < 0%}text-danger{%else%}text-success{%endif%}">{{ crypto.price_change_percentage_24h }}%</span>
            </p>
            <div>
                <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}" class="btn btn-primary btn-sm">Ver mais</a>
                <a href="{% url 'crypto_detail' crypto.cryptocurrency.id %}?showmodal=true" class="btn btn-warning btn-sm">Ativar alerta</a>
            </div>
            <small class="text-secondary">Atualizado há {{ crypto.timestamp|timesince }}</small>
        </div>
</div>
{% endfor %}
</div>

{% endblock content%}